\clearpage
\appendix
# (APPENDIX) Appendix {-}

# Original statements and used translation {#translate}

```{r atop-translation-kids, message=FALSE, warning=FALSE, include=TRUE,  echo = FALSE}
atop_key_groups <- atop_key %>%
  arrange(question_group) %>%
  mutate(row_number = row_number()) %>%
  group_by(question_group) %>%
  summarize(first = min(row_number),
            last = max(row_number)) %>% as.data.frame()
tbl <- atop_key %>%
  dplyr::select(question_text_english, question_text_french,
                question_text_dutch) %>%
  kable("latex", longtable = TRUE, booktabs = TRUE,
        caption = "The ATOP scale questions for the children's survey.",
        col.names = c("Original", "French", "Dutch")) %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 9) %>%
  column_spec(1:3, width = "3in") %>%
  landscape()
for (row in seq(1, nrow(atop_key_groups))) {
  tbl <- tbl %>%
    kableExtra::group_rows(atop_key_groups[row,1], start_row = atop_key_groups[row,2],
               end_row = atop_key_groups[row,3], underline = TRUE)
}
tbl
```


```{r nc-translation, message=FALSE, warning=FALSE, include=TRUE,  echo = FALSE}
tbl <- nc_key %>%
  dplyr::select(question_text_english, question_text_french,
                question_text_dutch) %>%
  kable("latex", longtable = TRUE, booktabs = TRUE,
        caption = "The Nature connectedness scale questions for the children's survey.",
        col.names = c("Original", "French", "Dutch")) %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 9) %>%
  column_spec(1:3, width = "3in") %>%
  landscape()
tbl
```


```{r atop-translation, message=FALSE, warning=FALSE, include=TRUE,  echo = FALSE}
tbl <- atop_key_p %>%
  mutate(question_text_english = ifelse(
    ommit_if_short_survey,
    paste0(question_text_english, "*"),
    question_text_english
  )) %>%
  dplyr::select(question_text_english, question_text_french,
                question_text_dutch) %>%
  kable("latex", longtable = TRUE, booktabs = TRUE,
        caption = "The outdoor play questions for the parents and guardians. Questions with a * are omitted in the shortened survey.",
        col.names = c("Original", "French", "Dutch")) %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 9) %>%
  column_spec(1:3, width = "3in") %>%
  landscape()
tbl
```

```{r reps-translation, message=FALSE, warning=FALSE, include=TRUE,  echo = FALSE}
tbl <- reps_key %>%
  mutate(question_text_english = ifelse(
    ommit_if_short_survey,
    paste0(question_text_english, "*"),
    question_text_english
  )) %>%
  dplyr::select(question_text_english, question_text_french,
                question_text_dutch) %>%
  kable("latex", longtable = TRUE, booktabs = TRUE,
        caption = "The REPS scale questions for parents and guardians. Questions with a * are omitted in the shortened survey.",
        col.names = c("Original", "French", "Dutch")) %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 9) %>%
  column_spec(1:3, width = "3in") %>%
  landscape()
tbl
```

```{r im-translation, message=FALSE, warning=FALSE, include=TRUE,  echo = FALSE}
tbl <- im_key %>%
  mutate(question_text_english = ifelse(
    ommit_if_short_survey,
    paste0(question_text_english, "*"),
    question_text_english
  )) %>%
  dplyr::select(question_text_english, question_text_french,
                question_text_dutch) %>%
  kable("latex", longtable = TRUE, booktabs = TRUE,
        caption = "The IM scale questions for parents and guardians. Questions with a * are omitted in the shortened survey.",
        col.names = c("Original", "French", "Dutch")) %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 9) %>%
  column_spec(1:3, width = "3in") %>%
  landscape()
tbl
```
